### ISSUE TITLE
Not working for English Client

### ISSUE THREAD

**Issue by Metoku** [Gattxxa/StarRailDiscordRPC#1]
Hello, I would like to request to make this program work for English named window. Thank you!

**Comment by Gattxxa** [comment]
Hello, A version that supports the English named window has been created. Please check if it is working correctly. Thank you for your request.  
→ [**Download Release v1.2.1**](https://github.com/Gattxxa/StarRailDiscordRPC/releases/tag/v1.2.1)  

<img width="316" alt="スクリーンショット 2023-05-24 14 07 07" src="https://github.com/Gattxxa/StarRailDiscordRPC/assets/61118664/dff4895f-f56f-4d98-a1df-bc66dd12e116">

**Comment by Metoku** [comment]
It is working correctly. Thank you for your hard work!
